### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by matt-kempster** [sayanarijit/moodlmth#6]
During setup, I encounter this issue:
```
kempster@Computer-Room:/mnt/c/Users/Matt/Documents/git_cloned/moodlmth$ python3 -m virtualenv html_thing
Using base prefix '/usr'
New python executable in /mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/bin/python3.7
Also creating executable in /mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/bin/python
Installing setuptools, pip, wheel...
done.

kempster@Computer-Room:/mnt/c/Users/Matt/Documents/git_cloned/moodlmth$ source html_thing/bin/activate
(html_thing) kempster@Computer-Room:/mnt/c/Users/Matt/Documents/git_cloned/moodlmth$ pip --version
pip 19.1.1 from /mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/pip (python 3.7)
(html_thing) kempster@Computer-Room:/mnt/c/Users/Matt/Documents/git_cloned/moodlmth$ pip install -r requirements.txt 
Collecting black==19.3b0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/30/62/cf549544a5fe990bbaeca21e9c419501b2de7a701ab0afb377bc81676600/black-19.3b0-py36-none-any.whl
Collecting htmldoom>=0.6<0.7 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/87/d4/9729d39b1287397cb42d26b9efd75447ec6bb8b89476280d67c6d9854b7e/htmldoom-0.6.5-py3-none-any.whl
Collecting htmlmin==0.1.12 (from -r requirements.txt (line 3))
Collecting requests==2.22.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting attrs>=18.1.0 (from black==19.3b0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting click>=6.5 (from black==19.3b0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting appdirs (from black==19.3b0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from black==19.3b0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.22.0->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests==2.22.0->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.22.0->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.22.0->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Installing collected packages: attrs, click, appdirs, toml, black, htmldoom, htmlmin, chardet, idna, urllib3, certifi, requests
Successfully installed appdirs-1.4.3 attrs-19.1.0 black-19.3b0 certifi-2019.6.16 chardet-3.0.4 click-7.0 htmldoom-0.6.5 htmlmin-0.1.12 idna-2.8 requests-2.22.0 toml-0.10.0 urllib3-1.25.3

(html_thing) kempster@Computer-Room:/mnt/c/Users/Matt/Documents/git_cloned/moodlmth$ python --version
Python 3.7.2

(html_thing) kempster@Computer-Room:/mnt/c/Users/Matt/Documents/git_cloned/moodlmth$ python setup.py install
/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing 'v0.2.1' to '0.2.1'
  normalized_version,
running install
running bdist_egg
running egg_info
writing moodlmth.egg-info/PKG-INFO
writing dependency_links to moodlmth.egg-info/dependency_links.txt
writing entry points to moodlmth.egg-info/entry_points.txt
writing requirements to moodlmth.egg-info/requires.txt
writing top-level names to moodlmth.egg-info/top_level.txt
file moodlmth.py (for module moodlmth) not found
reading manifest file 'moodlmth.egg-info/SOURCES.txt'
writing manifest file 'moodlmth.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file moodlmth.py (for module moodlmth) not found
file moodlmth.py (for module moodlmth) not found
copying moodlmth.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying moodlmth.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying moodlmth.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying moodlmth.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying moodlmth.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying moodlmth.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    entry_points={"console_scripts": ["moodlmth = moodlmth.cli:main"]},
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/mnt/c/Users/Matt/Documents/git_cloned/moodlmth/html_thing/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by sayanarijit** [comment]
Thanks for reporting. This is weird. I tested on a Windows VM and it was installed.
@matt-kempster could you please do the following and let me know how it goes?

```
git checkout fix/windows-compatibility
pip install -e .
```

**Comment by sayanarijit** [comment]
FYI this is in PyPI. If you just want to install, you can do `pip install -U moodlmth`

**Comment by matt-kempster** [comment]
Cool, looks like that worked. Thanks!
